"""Criar tabelas4

Revision ID: 5ffdbca20806
Revises: 
Create Date: 2024-07-29 17:24:47.439005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffdbca20806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rateio_mensal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usina_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_rateio_mensal_usina', 'usina', ['usina_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rateio_mensal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rateio_mensal_usina', type_='foreignkey')
        batch_op.drop_column('usina_id')

    # ### end Alembic commands ###
